// frontend-sveltekit/src/lib/components/TeamContactCard.svelte
<script lang="ts">
  import type { Team } from '$lib/types'
  import Icon from '@iconify/svelte'

  export let teamId: string | null = null
  export let team: Team | null = null
  export let teams: Record<string, Team> | null = null

  const iconMap: Record<string, string> = {
    email: 'mailto:',
    phone: 'tel:',
    sms: 'sms:',
    web: '',
    slack: '',
    teams: '',
    pigeon: '',
    pagerduty: ''
  }

  const channelIcons: Record<string, string> = {
    email: 'mdi:email-outline',
    phone: 'mdi:phone-outline',
    sms: 'mdi:message-text-outline',
    web: 'mdi:web',
    slack: 'mdi:slack',
    teams: 'mdi:microsoft-teams',
    pigeon: 'mdi:owl',
    pagerduty: 'mdi:bell-ring-outline'
  }

  $: resolvedTeam = team ?? (teamId && teams ? teams[teamId] ?? null : null)
  $: reachOptions = resolvedTeam?.reachability ?? []

  const defaultChannelIcon = 'mdi:link-variant'

  function getChannelIcon(channel: string): string {
    return channelIcons[channel.toLowerCase()] ?? defaultChannelIcon
  }

  function formatChannel(channel: string) {
    return channel.replace(/[-_]/g, ' ').replace(/^\w|\s\w/g, (c) => c.toUpperCase())
  }

  function buildLink(channel: string, detail: string) {
    const prefix = iconMap[channel.toLowerCase()]
    if (prefix === undefined) {
      return null
    }
    if (!prefix) {
      return detail.startsWith('http') ? detail : detail.startsWith('//') ? detail : `https://${detail}`
    }
    return `${prefix}${detail}`
  }
</script>

{#if resolvedTeam}
  <div class="rounded-xl border border-gray-200 bg-white/5 p-4">
    <div class="text-sm font-semibold text-gray-300">Responsible Team</div>
    <h3 class="text-lg font-semibold text-white">{resolvedTeam.name}</h3>
    {#if resolvedTeam.description}
      <p class="mt-1 text-sm text-gray-400">{resolvedTeam.description}</p>
    {/if}
    {#if resolvedTeam.teamLead}
      <p class="mt-2 text-xs text-gray-500">Led by {resolvedTeam.teamLead}</p>
    {/if}

    <div class="mt-4">
      <div class="text-sm font-medium text-gray-300">How to reach them</div>
      {#if reachOptions.length}
        <ul class="mt-2 space-y-2 text-sm text-gray-200">
          {#each reachOptions as entry}
            <li class="flex items-center justify-between rounded-lg border border-gray-700/40 px-3 py-2">
              <div class="flex items-center gap-2">
                <Icon icon={getChannelIcon(entry.channel)} class="h-4 w-4 text-gray-400" aria-hidden="true" />
                <span>{formatChannel(entry.channel)}</span>
              </div>
              {#if buildLink(entry.channel, entry.detail)}
                <a
                  href={buildLink(entry.channel, entry.detail)}
                  target={entry.channel === 'web' ? '_blank' : undefined}
                  rel="noreferrer"
                  class="text-blue-400 hover:text-blue-300"
                >
                  {entry.detail}
                </a>
              {:else}
                <span class="text-gray-400">{entry.detail}</span>
              {/if}
            </li>
          {/each}
        </ul>
      {:else}
        <p class="mt-2 text-sm text-gray-500">No contact methods provided yet.</p>
      {/if}
    </div>
  </div>
{/if}

// frontend/components/TeamContactCard.vue
<template>
  <v-card
    v-if="hasTeamSource"
    :variant="flat ? 'text' : 'outlined'"
    :class="flat ? '' : 'ma-4'"
  >
    <v-card-title class="text-subtitle-1 d-flex align-center">
      <v-icon icon="mdi-shield-account" class="mr-2" color="primary" />
      Responsible Team
    </v-card-title>
    <v-divider />
    <template v-if="resolvedTeam">
      <v-card-text>
        <div class="text-h6 mb-1">{{ resolvedTeam.name }}</div>
        <div v-if="resolvedTeam.description" class="text-body-2 text-medium-emphasis">
          {{ resolvedTeam.description }}
        </div>
        <div v-if="resolvedTeam.teamLead" class="text-caption text-medium-emphasis mt-2">
          Led by {{ resolvedTeam.teamLead }}
        </div>
      </v-card-text>
      <v-divider />
      <v-card-text>
        <div class="text-subtitle-2 mb-2">How to reach them</div>
        <template v-if="reachOptions.length">
          <v-list density="compact" variant="flat">
            <v-list-item
              v-for="(entry, index) in reachOptions"
              :key="`${entry.channel}-${index}-${entry.detail}`"
            >
              <template #prepend>
                <v-icon :icon="resolveIcon(entry.channel)" color="primary" class="mr-2" />
              </template>
              <v-list-item-title>{{ formatChannel(entry.channel) }}</v-list-item-title>
              <v-list-item-subtitle>
                <a v-if="isLink(entry.channel)" :href="buildLink(entry.channel, entry.detail)">
                  {{ entry.detail }}
                </a>
                <span v-else>{{ entry.detail }}</span>
              </v-list-item-subtitle>
            </v-list-item>
          </v-list>
        </template>
        <v-alert
          v-else
          type="info"
          variant="tonal"
          density="compact"
        >
          No contact methods provided yet.
        </v-alert>
      </v-card-text>
    </template>
    <template v-else>
      <v-card-text>
        <v-skeleton-loader type="text@3" class="mb-2" />
        <v-skeleton-loader type="text@2" width="60%" />
      </v-card-text>
    </template>
  </v-card>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useTeams } from '~/composables/useTeams'
import type { Team, TeamReachOption } from '~/types'

interface Props {
  teamId?: string | null
  team?: Team | null
  flat?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  flat: false,
  team: null,
  teamId: null
})
const { data: teamsData } = await useTeams()
const resolvedTeam = computed<Team | null>(() => props.team ?? (props.teamId ? teamsData.value?.[props.teamId] ?? null : null))
const hasTeamSource = computed(() => !!props.team || !!props.teamId)
const reachOptions = computed<TeamReachOption[]>(() => resolvedTeam.value?.reachability ?? [])

const iconMap: Record<string, string> = {
  email: 'mdi-email-outline',
  slack: 'mdi-slack',
  phone: 'mdi-phone',
  teams: 'mdi-microsoft-teams',
  pigeon: 'mdi-bird',
  sms: 'mdi-message-processing',
  web: 'mdi-earth',
  pagerduty: 'mdi-bell-alert'
}

const linkTypes = new Set(['email', 'phone', 'sms', 'web'])

function resolveIcon(channel: string) {
  return iconMap[channel.toLowerCase()] ?? 'mdi-link-variant'
}

function formatChannel(channel: string) {
  return channel.replace(/[-_]/g, ' ').replace(/\b\w/g, char => char.toUpperCase())
}

function isLink(channel: string) {
  return linkTypes.has(channel.toLowerCase())
}

function buildLink(channel: string, detail: string) {
  const normalized = channel.toLowerCase()
  if (normalized === 'email') {
    return `mailto:${detail}`
  }
  if (normalized === 'phone' || normalized === 'sms') {
    return `tel:${detail}`
  }
  if (normalized === 'web') {
    return detail.startsWith('http') ? detail : `https://${detail}`
  }
  return detail
}
</script>
