// frontend/components/DiagramToolbar.vue
<template>
  <v-toolbar density="comfortable" class="diagram-toolbar" border>
    <v-toolbar-items>
      <v-btn
        icon="mdi-home"
        variant="text"
        :disabled="pending"
        @click="$emit('go-home')"
      />
    </v-toolbar-items>

    <v-toolbar-title v-if="label" class="toolbar-label">{{ label }}</v-toolbar-title>

    <v-spacer />

    <v-toolbar-items class="actions">
      <v-btn
        variant="text"
        :icon="hideIncomingConnections ? 'mdi-eye-off-outline' : 'mdi-eye-outline'"
        :color="hideIncomingConnections ? 'error' : 'primary'"
        :disabled="pending"
        @click="$emit('toggle-incoming')"
        :title="hideIncomingConnections ? 'Show incoming connections' : 'Hide incoming connections'"
      />
      <v-btn
        icon="mdi-bug-outline"
        color="secondary"
        variant="text"
        :disabled="pending"
        title="Log Mermaid UML"
        @click="$emit('log-diagram')"
      />
      <v-btn
        :icon="showLegend ? 'mdi-format-list-bulleted' : 'mdi-format-list-checkbox'"
        color="secondary"
        variant="text"
        :disabled="pending"
        :title="showLegend ? 'Hide legend' : 'Show legend'"
        @click="$emit('toggle-legend')"
      />
      <v-btn
        :icon="isDarkMode ? 'mdi-weather-night' : 'mdi-white-balance-sunny'"
        color="accent"
        variant="text"
        :disabled="pending"
        :title="isDarkMode ? 'Switch to light mode' : 'Switch to dark mode'"
        @click="$emit('toggle-dark-mode')"
      />
    </v-toolbar-items>
  </v-toolbar>
</template>

<script setup lang="ts">
interface Props {
  pending?: boolean
  hideIncomingConnections?: boolean
  showLegend: boolean
  isDarkMode: boolean
  label?: string
}

withDefaults(defineProps<Props>(), {
  pending: false,
  hideIncomingConnections: false,
  label: ''
})

defineEmits<{
  'go-home': []
  'toggle-incoming': []
  'toggle-legend': []
  'toggle-dark-mode': []
  'log-diagram': []
}>()
</script>

<style scoped>
.diagram-toolbar {
  width: 100%;
}

.toolbar-label {
  font-weight: 500;
  font-size: 0.95rem;
}

.actions {
  display: flex;
  gap: 4px;
}
</style>

// frontend-sveltekit/src/lib/components/DiagramToolbar.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'
  import Icon from '@iconify/svelte'

  const dispatch = createEventDispatcher<{
    goHome: void
    toggleLegend: void
    toggleDarkMode: void
    logDiagram: void
  }>()

  export let pending = false
  export let label = ''
  export let showLegend = true
  export let isDarkMode = false
</script>

<div class="flex items-center gap-3 border-b border-gray-800/60 bg-gray-950/70 px-4 py-2 text-sm text-gray-200">
  <button
    class="flex items-center gap-2 rounded-md border border-gray-700 px-3 py-1 text-gray-100 transition hover:bg-gray-800"
    on:click={() => dispatch('goHome')}
    disabled={pending}
  >
    <Icon icon="mdi:home-outline" class="h-4 w-4" aria-hidden="true" />
    <span>Home</span>
  </button>

  {#if label}
    <div class="text-sm text-gray-400">{label}</div>
  {/if}

  <div class="ml-auto flex items-center gap-2">
    <button
      class="flex items-center gap-2 rounded-md border border-gray-700 px-3 py-1 text-gray-200 hover:bg-gray-800"
      on:click={() => dispatch('toggleLegend')}
      disabled={pending}
    >
      {#if showLegend}
        <Icon icon="mdi:eye-off-outline" class="h-4 w-4" aria-hidden="true" />
        <span>Hide legend</span>
      {:else}
        <Icon icon="mdi:eye-outline" class="h-4 w-4" aria-hidden="true" />
        <span>Show legend</span>
      {/if}
    </button>
    <button
      class="flex items-center gap-2 rounded-md border border-gray-700 px-3 py-1 text-gray-200 hover:bg-gray-800"
      on:click={() => dispatch('toggleDarkMode')}
      disabled={pending}
    >
      {#if isDarkMode}
        <Icon icon="mdi:weather-sunny" class="h-4 w-4" aria-hidden="true" />
        <span>Light mode</span>
      {:else}
        <Icon icon="mdi:weather-night" class="h-4 w-4" aria-hidden="true" />
        <span>Dark mode</span>
      {/if}
    </button>
    <button
      class="flex items-center gap-2 rounded-md border border-gray-700 px-3 py-1 text-gray-200 hover:bg-gray-800"
      on:click={() => dispatch('logDiagram')}
      disabled={pending}
    >
      <Icon icon="mdi:note-text-outline" class="h-4 w-4" aria-hidden="true" />
      <span>Log</span>
    </button>
  </div>
</div>
