// frontend/components/EmptyState.vue
<template>
  <div class="loading-container">
    <div style="text-align: center; padding: 40px;">
      <div style="font-size: 4rem; color: #999;">{{ icon }}</div>
      <h2 style="color: #666; margin-top: 20px;">{{ title }}</h2>
      <p style="color: #999;">{{ message }}</p>
      <button
        v-if="onAction"
        @click="onAction"
        style="margin-top: 20px; padding: 12px 24px; background: #1976d2; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; font-weight: bold;"
      >
        {{ actionLabel }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  icon?: string
  title: string
  message: string
  actionLabel?: string
  onAction?: () => void
}>()
</script>

<style scoped>
button:hover {
  opacity: 0.9;
}
</style>

// frontend-sveltekit/src/lib/components/EmptyState.svelte
Y<script lang="ts">
  export let icon = '📦'
  export let title = 'Nothing to show'
  export let message = ''
  export let actionLabel: string | null = null
  export let onAction: (() => void) | null = null
</script>

<div class="flex h-full w-full items-center justify-center p-8">
  <div class="max-w-md rounded-xl border border-gray-200 bg-white/5 p-8 text-center shadow">
    <div class="text-4xl" aria-hidden="true">{icon}</div>
    <h2 class="mt-4 text-xl font-semibold text-gray-100">{title}</h2>
    {#if message}
      <p class="mt-2 text-base text-gray-400">{message}</p>
    {/if}
    {#if actionLabel && onAction}
      <button
        class="mt-6 w-full rounded-md bg-blue-600 py-2 text-white transition hover:bg-blue-500"
        on:click={onAction}
      >
        {actionLabel}
      </button>
    {/if}
  </div>
</div>
