// frontend/components/ErrorDisplay.vue
<template>
  <div class="loading-container">
    <div style="max-width: 600px;">
      <v-card class="pa-6" variant="outlined">
        <v-card-title class="text-error d-flex align-center">
          <v-icon icon="mdi-alert" class="mr-2" />
          {{ title }}
        </v-card-title>
        <v-card-text>
          <p class="text-body-1">{{ message }}</p>
        </v-card-text>

        <v-card-text v-if="checkList?.length">
          <v-sheet class="pa-3" color="surface-variant" rounded="lg" variant="tonal">
            <div class="text-subtitle-2 mb-2">Please check:</div>
            <v-list density="compact">
              <v-list-item v-for="(item, index) in checkList" :key="index">
                <template #prepend>
                  <v-icon icon="mdi-check-circle" color="primary" class="mr-2" />
                </template>
                <v-list-item-title>{{ item }}</v-list-item-title>
              </v-list-item>
            </v-list>
          </v-sheet>
        </v-card-text>

        <v-card-text v-if="technicalDetails">
          <v-expansion-panels variant="accordion">
            <v-expansion-panel>
              <v-expansion-panel-title class="text-primary text-subtitle-2">
                <v-icon icon="mdi-code-tags" class="mr-2" />
                Technical Details
              </v-expansion-panel-title>
              <v-expansion-panel-text>
                <v-sheet color="surface-variant" rounded="lg" class="pa-3 position-relative">
                  <pre class="text-caption" style="white-space: pre-wrap; word-wrap: break-word;">{{ formattedDetails }}</pre>
                  <v-btn
                    class="copy-btn"
                    :color="isCopied ? 'success' : 'primary'"
                    size="small"
                    :text="isCopied ? 'Copied!' : 'Copy'"
                    :prepend-icon="isCopied ? 'mdi-check' : 'mdi-content-copy'"
                    @click="copyToClipboard"
                  />
                </v-sheet>
              </v-expansion-panel-text>
            </v-expansion-panel>
          </v-expansion-panels>
        </v-card-text>

        <v-card-actions class="justify-center mt-4">
          <v-btn
            v-if="onRetry"
            color="primary"
            variant="flat"
            prepend-icon="mdi-refresh"
            @click="onRetry"
          >Retry</v-btn>
          <v-btn
            v-if="onBack"
            color="secondary"
            variant="text"
            prepend-icon="mdi-arrow-left"
            @click="onBack"
          >Back to Overview</v-btn>
        </v-card-actions>
      </v-card>
    </div>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  title: string
  message: string
  technicalDetails?: any
  checkList?: string[]
  onRetry?: () => void
  onBack?: () => void
}>()

const isCopied = ref(false)

const formattedDetails = computed(() => {
  if (!props.technicalDetails) {
    return ''
  }
  return typeof props.technicalDetails === 'string'
    ? props.technicalDetails
    : JSON.stringify(props.technicalDetails, null, 2)
})

function copyToClipboard() {
  if (!formattedDetails.value) {
    return
  }
  navigator.clipboard.writeText(formattedDetails.value).then(() => {
    isCopied.value = true
    setTimeout(() => {
      isCopied.value = false
    }, 2000)
  })
}
</script>

<style scoped>
.copy-btn {
  position: absolute;
  top: 12px;
  right: 12px;
}
</style>

// frontend-sveltekit/src/lib/components/ErrorDisplay.svelte
<script lang="ts">
  import Icon from '@iconify/svelte';

  export let title = 'Something went wrong'
  export let message = 'An unexpected error occurred.'
  export let checkList: string[] = []
  export let technicalDetails: string | Record<string, unknown> | null = null
  export let onRetry: (() => void) | null = null
  export let onBack: (() => void) | null = null

  $: formattedDetails = technicalDetails
    ? typeof technicalDetails === 'string'
      ? technicalDetails
      : JSON.stringify(technicalDetails, null, 2)
    : ''

  let copied = false

  async function copyDetails() {
    if (!formattedDetails) return
    await navigator.clipboard.writeText(formattedDetails)
    copied = true
    setTimeout(() => (copied = false), 2000)
  }
</script>

<div class="flex h-full w-full items-center justify-center p-8">
  <div class="w-full max-w-2xl rounded-2xl border border-red-500/40 bg-red-500/10 p-6 shadow">
    <div class="flex items-center text-red-300">
      <Icon icon="mdi:alert-circle-outline" class="mr-2 h-7 w-7 text-red-400" aria-hidden="true" />
      <h2 class="big-title text-xl font-semibold">{title}</h2>
    </div>
    <p class="mt-2 text-base text-gray-700 dark:text-gray-200">{message}</p>

    {#if checkList.length}
      <div class="mt-4 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-100 dark:bg-slate-800 p-4">
        <p class="text-sm font-semibold text-gray-700 dark:text-gray-300">Please check:</p>
        <ul class="mt-2 list-disc space-y-1 pl-5 text-sm text-gray-600 dark:text-gray-400">
          {#each checkList as item}
            <li>{item}</li>
          {/each}
        </ul>
      </div>
    {/if}

    {#if formattedDetails}
      <div class="mt-4 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-100 dark:bg-slate-800 p-4">
        <div class="flex items-center justify-between">
          <span class="text-sm font-semibold text-gray-700 dark:text-gray-300">Technical details</span>
          <button class="text-sm text-blue-600 dark:text-blue-400 hover:text-blue-500 dark:hover:text-blue-300" on:click={copyDetails}>
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>
        <pre class="mt-2 max-h-48 overflow-auto rounded bg-gray-50 dark:bg-black/40 p-3 text-xs text-gray-700 dark:text-gray-300">{formattedDetails}</pre>
      </div>
    {/if}

    <div class="mt-6 flex flex-wrap gap-3">
      {#if onRetry}
        <button class="rounded-md bg-blue-600 px-4 py-2 text-sm text-white hover:bg-blue-500" on:click={onRetry}>
          Retry
        </button>
      {/if}
      {#if onBack}
        <button class="rounded-md border border-gray-300 dark:border-gray-700 px-4 py-2 text-sm text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800" on:click={onBack}>
          Back
        </button>
      {/if}
    </div>
  </div>
</div>
