// frontend/components/FlowCanvas.vue
<template>
  <div class="diagram-container">
    <DiagramToolbar
        :pending="pending"
        :can-go-back="canGoBack"
        :hide-incoming-connections="hideIncomingConnections"
        :hide-external-to-external="hideExternalToExternal"
        :show-legend="showLegend"
        :is-dark-mode="isDarkMode.value"
        @go-home="emit('goHome')"
        @go-back="emit('goBack')"
        @toggle-incoming="emit('toggleIncomingConnections')"
        @toggle-external-to-external="emit('toggleExternalToExternal')"
        @toggle-legend="showLegend = !showLegend"
        @toggle-dark-mode="toggleDarkMode"
        @log-diagram="logCurrentDiagram"
    />

    <div class="diagram-surface" :class="{ 'is-loading': pending }" ref="diagramSurfaceRef">
      <ClientOnly>
        <VueMermaidString
            v-show="renderableDiagram"
            :key="diagramRenderKey"
            :value="renderableDiagram"
            :options="mermaidOptions"
            @node-click="onMermaidNodeClick"
            @parse-error="handleParseError"
        />
      </ClientOnly>
      <div v-if="!hasDiagram && !pending" class="diagram-placeholder">
        <slot name="empty">No diagram available.</slot>
      </div>
    </div>

    <div v-if="showLegend && !pending" class="floating-legend">
      <Legend/>
    </div>

    <v-alert
      v-if="parseError"
      type="error"
      class="diagram-error"
      variant="tonal"
      density="compact"
    >
      {{ parseError }}
    </v-alert>
  </div>
</template>

<script setup lang="ts">
import VueMermaidString from 'vue-mermaid-string'
import type {MermaidConfig} from 'mermaid'
import mermaid from 'mermaid'
import { useTheme } from 'vuetify'
import Legend from '~/components/Legend.vue'
import DiagramToolbar from '~/components/DiagramToolbar.vue'
import {withDiagramConfig} from '~/utils/mermaid/diagramHelpers'

interface Props {
  diagram: string
  pending?: boolean
  showToolbar?: boolean
  canGoBack?: boolean
  hideIncomingConnections?: boolean
  hideExternalToExternal?: boolean
  mermaidOptions?: MermaidConfig
}

const props = withDefaults(defineProps<Props>(), {
  diagram: '',
  pending: false,
  showToolbar: false,
  canGoBack: false,
  hideIncomingConnections: false,
  hideExternalToExternal: false,
  mermaidOptions: () => ({})
})

const emit = defineEmits<{
  nodeClick: [nodeId: string]
  nodeDoubleClick: [nodeId: string]
  goHome: []
  goBack: []
  toggleIncomingConnections: []
  toggleExternalToExternal: []
}>()

const showLegend = ref(true)
const parseError = ref<string>('')
const PLACEHOLDER_DIAGRAM = 'architecture-beta\nservice placeholder(server)["No data yet"]'

const hasDiagram = computed(() => !!props.diagram?.trim())
const renderableDiagram = computed(() =>
    hasDiagram.value
        ? withDiagramConfig(props.diagram)
        : PLACEHOLDER_DIAGRAM
)
const diagramRenderKey = computed(() => `${renderableDiagram.value}::${isDarkMode.value ? 'dark' : 'default'}`)

const theme = useTheme()
const isDarkMode = computed(() => theme.global.current.value.dark)

const mermaidOptions = computed(() => ({
  theme: isDarkMode.value ? 'dark' : 'default',
  securityLevel: 'loose',
  logLevel: 'info',
  architecture: {
    padding: 32
  },
  flowchart: {
    htmlLabels: true,
    curve: 'basis'
  },
  ...props.mermaidOptions
}))

watch(() => props.diagram, () => {
  parseError.value = ''
})

watch(renderableDiagram, () => {
  if (!import.meta.client) {
    return
  }
})

onMounted(() => {
  if (!import.meta.client) {
    return
  }
  const savedTheme = localStorage.getItem('preferredTheme')
  if (savedTheme === 'dark' || savedTheme === 'light') {
    theme.global.name.value = savedTheme
  }
})


console.debug('[Mermaid Icons] Registering Mermaid icon packs for current view')
try {
  mermaid.registerIconPacks([
    {
      name: 'logos',
      loader: () => {
        console.debug("[Mermaid Icons] Loading 'logos' icon pack from unpkg.com");
        return import('@iconify-json/logos').then((module) => module.icons);
      }
    }
  ])
  console.debug('[Mermaid Icons] Icon packs ready')
} catch (error) {
  console.warn('Unable to register AWS icon pack for mermaid:', error)
}


const DOUBLE_CLICK_THRESHOLD_MS = 400
let lastClickedNode: string | null = null
let lastClickTimestamp = 0

function toggleDarkMode() {
  const nextTheme = isDarkMode.value ? 'light' : 'dark'
  theme.global.name.value = nextTheme
  if (import.meta.client) {
    localStorage.setItem('preferredTheme', nextTheme)
  }
}

function onMermaidNodeClick(nodeId: string) {
  const now = Date.now()
  if (lastClickedNode === nodeId && now - lastClickTimestamp <= DOUBLE_CLICK_THRESHOLD_MS) {
    emit('nodeDoubleClick', nodeId)
    lastClickedNode = null
    lastClickTimestamp = 0
    return
  }
  lastClickedNode = nodeId
  lastClickTimestamp = now
  emit('nodeClick', nodeId)
}

function handleParseError(error: unknown) {
  if (error instanceof Error) {
    parseError.value = error.message
  } else {
    parseError.value = 'Failed to render diagram.'
  }
}

function logCurrentDiagram() {
  const diagram = renderableDiagram.value
  if (!import.meta.client) {
    return
  }
  if (!diagram?.trim()) {
    console.info('[Mermaid UML] No diagram available yet')
  } else if (diagram === PLACEHOLDER_DIAGRAM) {
    console.info('[Mermaid UML] Placeholder diagram rendered')
  } else {
    console.info('[Mermaid UML]', '\n' + diagram)
  }
}
</script>

<style scoped>
.diagram-container {
  position: relative;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
}

.diagram-surface {
  flex: 1;
  overflow: auto;
  padding: 16px;
}

.diagram-surface.is-loading {
  opacity: 0.6;
  pointer-events: none;
}

.diagram-placeholder {
  width: 100%;
  height: 100%;
  border: 1px dashed currentColor;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.floating-legend {
  position: absolute;
  bottom: 24px;
  right: 24px;
  z-index: 3;
  max-width: 320px;
}

.diagram-error {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
}
</style>

// frontend-sveltekit/src/lib/components/FlowCanvas.svelte
<script lang="ts">
  import { createEventDispatcher, onDestroy, onMount } from 'svelte'
  import mermaid from 'mermaid'
  import DiagramToolbar from '$lib/components/DiagramToolbar.svelte'
  import Legend from '$lib/components/Legend.svelte'
  import { withDiagramConfig } from '$lib/utils/mermaid/diagramHelpers'

  const DOUBLE_CLICK_THRESHOLD = 400

  export let diagram = ''
  export let pending = false
  export let label = ''
  export let showToolbar = true

  const dispatch = createEventDispatcher<{
    nodeClick: string
    nodeDoubleClick: string
    goHome: void
  }>()

  let container: HTMLDivElement | null = null
  let isDarkMode = false
  let showLegend = true
  let parseError = ''
  let lastClickedNode: string | null = null
  let lastClickTimestamp = 0
  let renderCounter = 0
  let mounted = false
  let emptyStateLabel = 'No diagram available.'
  let dataSignature = ''

  const normalizeNodeId = (nodeId: string) => nodeId.replace(/^flowchart-/, '').replace(/-\d+$/, '')

  function scheduleRender(reason: string) {
    if (!mounted) {
      return
    }
    renderCounter += 1
    const renderId = renderCounter
    console.debug('[FlowCanvas] scheduleRender', { reason, renderId })
    queueMicrotask(() => {
      if (mounted) {
        renderDiagram(renderId)
      }
    })
  }

  const handleResize = () => {
    scheduleRender('resize')
  }

  onMount(() => {
    mounted = true
    const stored = typeof window !== 'undefined' ? localStorage.getItem('preferredTheme') : null
    if (stored === 'dark') {
      isDarkMode = true
      document.documentElement.classList.add('dark')
    }
    mermaid.initialize({ startOnLoad: false, securityLevel: 'loose', theme: isDarkMode ? 'dark' : 'default' })
    const resizeObserver = new ResizeObserver(() => handleResize())
    if (container) {
      resizeObserver.observe(container)
    }
    window.addEventListener('resize', handleResize)
    scheduleRender('mount')
    return () => {
      mounted = false
      resizeObserver.disconnect()
      window.removeEventListener('resize', handleResize)
    }
  })

  onDestroy(() => {
    mounted = false
  })

  $: if (mounted) {
    const signature = `${diagram?.trim() ?? ''}:${pending}`
    if (signature !== dataSignature) {
      dataSignature = signature
      console.debug('[FlowCanvas] data signature changed', signature)
      scheduleRender('data-change')
    }
  }

  async function renderDiagram(renderId?: number) {
    const targetRenderId = renderId ?? renderCounter
    console.debug('[FlowCanvas] renderDiagram invoked', { hasDiagram: !!diagram?.trim(), pending, targetRenderId })
    if (!container || !mounted) {
      return
    }
    if (!diagram?.trim()) {
      container.innerHTML = ''
      parseError = ''
      emptyStateLabel = pending ? 'Rendering diagram…' : 'No diagram available.'
      console.debug('[FlowCanvas] renderDiagram empty state', { pending })
      return
    }
    try {
      mermaid.initialize({ startOnLoad: false, securityLevel: 'loose', theme: isDarkMode ? 'dark' : 'default' })
      const { svg } = await mermaid.render(`diagram-${targetRenderId}`, withDiagramConfig(diagram))
      container.innerHTML = svg
      console.debug('[FlowCanvas] renderDiagram success', { id: `diagram-${targetRenderId}` })
      attachNodeListeners()
      parseError = ''
    } catch (error) {
      parseError = error instanceof Error ? error.message : 'Failed to render diagram.'
      console.error('[FlowCanvas] renderDiagram error', error)
    }
  }

  function attachNodeListeners() {
    if (!container) return
    container.querySelectorAll('.node').forEach(node => {
      node.addEventListener('click', handleNodeClick as EventListener)
    })
  }

  function handleNodeClick(event: Event) {
    const target = event.currentTarget as HTMLElement | null
    if (!target?.id) {
      return
    }
    const rawNodeId = target.id
    const nodeId = normalizeNodeId(rawNodeId)
    const now = Date.now()
    console.debug('[FlowCanvas] node click received', { rawNodeId, nodeId })
    if (lastClickedNode === nodeId && now - lastClickTimestamp <= DOUBLE_CLICK_THRESHOLD) {
      dispatch('nodeDoubleClick', nodeId)
      console.debug('[FlowCanvas] double click emitted', nodeId)
      lastClickedNode = null
      lastClickTimestamp = 0
      return
    }
    lastClickedNode = nodeId
    lastClickTimestamp = now
    dispatch('nodeClick', nodeId)
  }

  function toggleLegend() {
    showLegend = !showLegend
    console.debug('[FlowCanvas] toggleLegend', showLegend)
  }

  function toggleDarkMode() {
    isDarkMode = !isDarkMode
    console.debug('[FlowCanvas] toggleDarkMode', isDarkMode)
    if (isDarkMode) {
      document.documentElement.classList.add('dark')
      localStorage.setItem('preferredTheme', 'dark')
    } else {
      document.documentElement.classList.remove('dark')
      localStorage.setItem('preferredTheme', 'light')
    }
    scheduleRender('theme-change')
  }

  function logDiagram() {
    if (!diagram?.trim()) {
      console.info('[FlowCanvas] No diagram to log yet')
      return
    }
    console.info('[FlowCanvas]\n' + diagram)
  }

  function handleToolbarHome() {
    console.debug('[FlowCanvas] toolbar goHome triggered')
    dispatch('goHome')
  }
</script>

<div data-testid="flow-canvas" class="relative flex h-full min-h-0 flex-1 flex-col bg-gradient-to-b from-slate-950 to-slate-900">
  {#if showToolbar}
    <DiagramToolbar
      {pending}
      {label}
      {showLegend}
      {isDarkMode}
      on:goHome={handleToolbarHome}
      on:toggleLegend={toggleLegend}
      on:toggleDarkMode={toggleDarkMode}
      on:logDiagram={logDiagram}
    />
  {/if}

  <div class="relative flex-1 overflow-auto">
    <div bind:this={container} class="min-h-full p-4 text-white" aria-live="polite" aria-busy={pending}></div>
    {#if pending}
      <div class="pointer-events-none absolute inset-0 flex items-center justify-center bg-black/40 text-sm text-gray-200 backdrop-blur">
        Rendering diagram…
      </div>
    {:else if !diagram?.trim()}
      <div class="absolute inset-0 flex flex-col items-center justify-center gap-2 text-sm text-gray-400">
        <span class="text-3xl" aria-hidden="true">🌀</span>
        <span>{emptyStateLabel}</span>
      </div>
    {/if}
    {#if showLegend && !pending}
      <div class="pointer-events-none absolute bottom-4 right-4"><Legend /></div>
    {/if}
  </div>

  {#if parseError}
    <div class="border-t border-red-500/40 bg-red-500/10 px-4 py-2 text-sm text-red-300">{parseError}</div>
  {/if}
</div>
