// frontend/components/ServiceDetailSidebar.vue
<template>
  <aside class="sidebar">
    <v-sheet class="d-flex flex-column fill-height" elevation="0">
      <v-card variant="outlined" class="ma-4">
        <v-card-text>
          <div class="text-caption text-uppercase text-medium-emphasis">Current Group</div>
          <div class="text-h6">{{ group.name }}</div>
          <div v-if="group.description" class="text-body-2 mt-2 text-medium-emphasis">{{ group.description }}</div>
          <div class="text-caption mt-2">ID: {{ group.groupName }}</div>
        </v-card-text>
      </v-card>

      <TeamContactCard v-if="group.teamId" :team-id="group.teamId" />

      <v-card variant="outlined" class="ma-4">
        <v-card-text class="d-flex align-center justify-space-between">
          <div>
            <div class="text-caption text-uppercase">Service</div>
            <div class="text-h6 mt-1">{{ service ? service.friendlyName : 'Select a service' }}</div>
          </div>
          <v-btn
            v-if="service"
            icon="mdi-close"
            variant="text"
            density="comfortable"
            @click="$emit('clear-service')"
            :aria-label="'Clear selected service'"
          />
        </v-card-text>
        <v-divider />
        <v-card-text v-if="service">
          <div class="text-caption text-medium-emphasis">{{ service.identifier }}</div>
          <v-chip class="mt-3" color="secondary" text-color="white" variant="flat">
            {{ service.serviceType }}
          </v-chip>
          <v-alert
            v-if="isExternalService && serviceGroup"
            type="info"
            variant="tonal"
            density="compact"
            class="mt-3"
          >
            This service belongs to {{ serviceGroup.name }}
          </v-alert>
          <p v-if="service.description" class="mt-4 text-body-2">{{ service.description }}</p>
          <div v-else class="text-caption text-medium-emphasis mt-4">No description provided.</div>
        </v-card-text>
        <v-card-text v-else class="text-caption text-medium-emphasis">
          Click a service node in the diagram to see its details here.
        </v-card-text>
      </v-card>

      <v-card
        v-if="isExternalService && serviceGroup"
        variant="outlined"
        class="ma-4"
      >
        <v-card-text>
          <div class="text-caption text-uppercase text-medium-emphasis">Target Group</div>
          <div class="text-h6">{{ serviceGroup.name }}</div>
          <div v-if="serviceGroup.description" class="text-body-2 mt-2 text-medium-emphasis">
            {{ serviceGroup.description }}
          </div>
          <div class="text-caption mt-2">ID: {{ serviceGroup.groupName }}</div>
        </v-card-text>
      </v-card>

      <TeamContactCard
        v-if="isExternalService && serviceGroup?.teamId"
        :team-id="serviceGroup.teamId"
      />
    </v-sheet>
  </aside>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import TeamContactCard from '~/components/TeamContactCard.vue'
import type { GroupInfo, ServiceDefinition } from '~/types'

interface Props {
  group: GroupInfo
  service?: ServiceDefinition | null
  serviceGroup?: GroupInfo | null
}

const props = defineProps<Props>()

const isExternalService = computed(() => {
  if (!props.service || !props.serviceGroup) {
    return false
  }
  return props.serviceGroup.groupName !== props.group.groupName
})

defineEmits<{ 'clear-service': [] }>()
</script>

<style scoped>
.sidebar {
  width: 340px;
  max-width: 35vw;
  height: 100%;
  display: flex;
  flex-direction: column;
}
</style>

// frontend-sveltekit/src/lib/components/ServiceDetailSidebar.svelte
<script lang="ts">
  import type { GroupInfo, ServiceDefinition, Team } from '$lib/types'
  import TeamContactCard from '$lib/components/TeamContactCard.svelte'
  import { createEventDispatcher } from 'svelte'

  export let group: GroupInfo | null = null
  export let service: ServiceDefinition | null = null
  export let serviceGroup: GroupInfo | null = null
  export let teams: Record<string, Team> | null = null

  const dispatch = createEventDispatcher<{ clearSelection: void }>()

  const isExternalService = () => {
    if (!group || !service || !serviceGroup) {
      return false
    }
    return serviceGroup.groupName !== group.groupName
  }
</script>

<aside class="flex h-full w-96 flex-col border-l border-gray-900/70 bg-gray-950/70">
  <div class="flex-1 overflow-y-auto p-4">
    {#if !group}
      <div class="rounded-xl border border-gray-800/60 bg-gray-900/40 p-4 text-sm text-gray-400">
        Select a group to view details.
      </div>
    {:else}
      <div class="rounded-xl border border-gray-800/60 bg-gray-900/40 p-4">
        <div class="text-xs uppercase tracking-wide text-gray-500">Current Group</div>
        <h2 class="text-xl font-semibold text-white">{group.name}</h2>
        {#if group.description}
          <p class="mt-2 text-sm text-gray-400">{group.description}</p>
        {/if}
        <p class="mt-3 text-xs text-gray-500">ID: {group.groupName}</p>
        {#if group.teamId}
          <div class="mt-4">
            <TeamContactCard teamId={group.teamId} teams={teams ?? undefined} />
          </div>
        {/if}
      </div>

      <div class="mt-4 rounded-xl border border-gray-800/60 bg-gray-900/40 p-4">
        <div class="flex items-center justify-between">
          <div>
            <div class="text-xs uppercase tracking-wide text-gray-500">Service</div>
            <h3 class="text-lg font-semibold text-white">
              {service ? service.friendlyName : 'Select a service'}
            </h3>
          </div>
          {#if service}
            <button
              class="rounded-full border border-gray-600 px-3 py-1 text-xs text-gray-300 hover:bg-gray-800"
              on:click={() => dispatch('clearSelection')}
            >
              Clear
            </button>
          {/if}
        </div>
        {#if service}
          <div class="mt-3 text-sm text-gray-400">{service.description ?? 'No description provided.'}</div>
          <div class="mt-4 text-xs text-gray-500">ID: {service.identifier}</div>
          <div class="mt-2 inline-flex rounded-full border border-blue-500/40 px-3 py-1 text-xs text-blue-300">
            {service.serviceType}
          </div>
        {:else}
          <p class="mt-4 text-sm text-gray-500">Click a service node to inspect its details.</p>
        {/if}
      </div>

      {#if isExternalService() && serviceGroup}
        <div class="mt-4 rounded-xl border border-amber-400/40 bg-amber-500/10 p-4">
          <div class="text-xs uppercase tracking-wide text-amber-200">External Service</div>
          <h3 class="text-lg font-semibold text-white">{serviceGroup.name}</h3>
          {#if serviceGroup.description}
            <p class="mt-2 text-sm text-amber-100">{serviceGroup.description}</p>
          {/if}
          <p class="mt-3 text-xs text-amber-200/80">ID: {serviceGroup.groupName}</p>
          {#if serviceGroup.teamId}
            <div class="mt-4">
              <TeamContactCard teamId={serviceGroup.teamId} teams={teams ?? undefined} />
            </div>
          {/if}
        </div>
      {/if}
    {/if}
  </div>
</aside>
